replicaCount: 4

image:
  repository: mujagicamer/cloud-native-user-service
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: true
  host: user.test

config:
  APP_ENV: production
  PORT: "3000"